# Open BB Terminal
Explorer

In [2]:
import pandas as pd
import numpy as np
import json
import requests
from openbb import obb

In [ ]:
# Equity assets, overview
obb.equity.price.quote(symbol="AAPL", provider="yfinance").to_df()
# quote_data.to_df().T

,symbol,asset_type,name,exchange,bid,bid_size,ask,ask_size,last_price,open,...,low,volume,prev_close,year_high,year_low,ma_50d,ma_200d,volume_average,volume_average_10d,currency
0,AAPL,EQUITY,Apple Inc.,NMS,330.31,2,337.05,1,336.13,337.99,...,332.53,86241049,337.0,344.57,240.21,320.1422,286.3412,53449420.0,49158440.0,USD

In [10]:
# Treasury rates
df_fi = obb.fixedincome.government.treasury_rates()
df_fi.to_df()

,month_1,month_3,month_6,year_1,year_2,year_3,year_5,year_7,year_10,year_20,year_30
date,,,,,,,,,,,
2025-09-19,0.0419,0.0403,0.0381,0.0360,0.0357,0.0356,0.0368,0.0388,0.0414,0.0471,0.0475
2025-09-22,0.0417,0.0400,0.0381,0.0361,0.0361,0.0359,0.0371,0.0390,0.0415,0.0473,0.0477
2025-09-23,0.0416,0.0400,0.0381,0.0361,0.0353,0.0357,0.0368,0.0387,0.0412,0.0470,0.0473
2025-09-24,0.0418,0.0402,0.0382,0.0363,0.0357,0.0360,0.0370,0.0391,0.0416,0.0473,0.0476
2025-09-25,0.0424,0.0404,0.0385,0.0368,0.0364,0.0366,0.0375,0.0394,0.0418,0.0473,0.0475
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-11,0.0393,0.0407,0.0412,0.0435,0.0463,0.0469,0.0478,0.0487,0.0496,0.0538,0.0535
2026-09-14,0.0394,0.0411,0.0418,0.0437,0.0465,0.0473,0.0480,0.0488,0.0497,0.0537,0.0534
2026-09-15,0.0393,0.0411,0.0417,0.0439,0.0467,0.0476,0.0483,0.0491,0.0500,0.0540,0.0536
2026-09-16,0.0396,0.0414,0.0422,0.0445,0.0474,0.0482,0.0486,0.0494,0.0501,0.0539,0.0535
2026-09-17,0.0397,0.0412,0.0420,0.0440,0.0467,0.0475,0.0478,0.0486,0.0494,0.0532,0.0529

In [16]:
df_fi.extra

{'metadata': Metadata

 arguments: {'provider_choices': {'provider': 'federal_reserve'}, 'standard_params': {}, 'extra_params': {}}
 duration: 1332843700
 route: /fixedincome/government/treasury_rates
 timestamp: 2026-09-19 00:00:44.605130}

In [17]:
from openbb_core.provider.standard_models.calendar_events import (
CalendarEventsData,
CalendarEventsQueryParams,
)

NameError: name 'self' is not defined